-- SQL-dialect for PostgreSQL

-- start Docker PostgreSQL in container: just copy-paste in terminal text below
-- docker run -d -p 5432:5432 --rm -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres_handmade_mplace --name postgres_handmade_mplace -it postgres

-- person_id int generated by default as identity SIMILAR person_id serial

create table persons (
    person_id int primary key generated by default as identity ,
    username varchar(24) check ( length(username) >= 4 ) unique not null ,
    full_name varchar(100) check ( length(full_name) >= 2 ) ,
    description text ,
    path_to_avatar text
);

-- create table person_auth (
--     person_id int primary key references person(person_id) on delete cascade ,
--     login varchar(24) primary key unique ,
--     password varchar(40) check ( length(password) >= 8 )
-- );

create table persons_props (
    person_id int primary key references persons(person_id) on delete cascade ,
    telegram varchar(100) unique ,
    phone_number varchar(13) unique ,
    email varchar(100) unique ,
    registration_date timestamp not null
);

create table items (
    item_id serial primary key ,
    person_id int references persons(person_id) on delete cascade ,
    name varchar(100) not null ,
    description text ,
    price float
);

create table categories (
    category_id serial primary key ,
    name varchar(50) not null
);

create table items_categories (
    item_id int references items(item_id) on delete cascade ,
    category_id int references categories(category_id) on delete set null ,
    primary key (item_id, category_id)
);

create table items_imgs (
    img_id serial primary key ,
    item_id int references items(item_id) on delete cascade ,
    path_to_img text
);

-- Drop all tables

-- drop table items_imgs;
-- drop table items_categories;
-- drop table categories;
-- drop table items;
-- drop table persons_props;
-- drop table persons;

insert into categories(name) values ('Home & Living'); --1
insert into categories(name) values ('Art & Collectibles'); --2
insert into categories(name) values ('Jewelry'); --3
insert into categories(name) values ('Clothing'); --4
insert into categories(name) values ('Accessories'); --5
insert into categories(name) values ('Bath & Beauty'); --6
insert into categories(name) values ('Pottery'); --7
insert into categories(name) values ('Toys & Games'); --8
insert into categories(name) values ('Bugs & Purses'); --9
insert into categories(name) values ('Weddings'); --10
insert into categories(name) values ('Books'); --11
insert into categories(name) values ('Movie'); --12
insert into categories(name) values ('Musics'); --13



insert into persons(username, full_name, description, path_to_avatar) --1
values ('TEST_k08ZzZaR', 'Taras Hryhorovych Shevchenko',
        'And I''ll draw a picture, and I''ll write a poem, and I''ll kill all the Russians',
        'https://upload.wikimedia.org/wikipedia/commons/b/b2/Т._Г._Шевченко._Квітень_1859.jpg');

insert into persons(username, full_name, description, path_to_avatar) --2
values ('TEST_K0stenk0L1na', 'Lina Vasylivna Kostenko',
        'All literature from the heart, I don’t ask for money for myself, everything is donated to the Armed Forces of Ukraine',
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Lina_Kostenko.jpg/220px-Lina_Kostenko.jpg');

insert into persons(username, full_name, description, path_to_avatar) --3
values ('TEST_SSSkov0rodÅ', 'Hryhorii Savych Skovoroda',
        'I live quietly, I don''t bother anyone, I try to kill all Russians',
        'https://upload.wikimedia.org/wikipedia/commons/5/50/Григорий_Сковорода.jpg');



insert into persons_props(person_id, telegram, phone_number, email, registration_date)
values (1, null, +380238910234, 'taras4ever@ukr.net', '2022-08-19 10:41:08');

insert into persons_props(person_id, telegram, phone_number, email, registration_date)
values (2, 't.me/CinCAFU', +380123456789, 'lina_bone_in_home@ukr.net', '2022-11-25 10:41:08');

insert into persons_props(person_id, telegram, phone_number, email, registration_date)
values (3, 't.me/V_Zelenskiy_official', +380112233456, 'sko0oroda1722@ukr.net', '2023-02-10 10:41:08');



insert into items(person_id, name, description, price) --1
values (1, 'Картина Катерина', 'Написав картину до одноіманної поеми влітку 1842-го року. Тепер пропую її вам за донат на ЗСУ.',
        999.95);

insert into items_imgs(item_id, path_to_img)
values (1, 'http://surl.li/gfybp');

insert into items_categories (item_id, category_id)values (1, 2);
insert into items_categories (item_id, category_id)values (1, 5);

insert into items(person_id, name, description, price) --2
values (1, 'Кольє КОЛО маленька Карта України 40см срібло',
        'Я не виробляв цього кольє, а просто стиряв з розетки для тесту, кєк). ' ||
        'Кольє у формі карти України з цепочкою довжиною 40см. + підовжувач 5 см. Застібку можна перестібнути на довжину до 45 см.' ||
        'Вага 2,4г. Розмір 20х13 мм. Матеріал срібло 925 пробі. Уваковка – дерев''яна коробочка.',
        530);

insert into items_imgs(item_id, path_to_img)
values (2, 'https://content.rozetka.com.ua/goods/images/big/277059714.jpg');
insert into items_imgs(item_id, path_to_img)
values (2, 'https://content1.rozetka.com.ua/goods/images/big/277059721.jpg');

insert into items_categories (item_id, category_id)values (2, 3);

insert into items(person_id, name, description, price) --3
values (2, 'Ваза Сідниця 28см біла',
        'Чудова ваза для вашої вітальні та на подарунок, наприклад до керівника відділу. ' ||
        'Ви можете неймовірно урізноманітнити ваш інтерʼєр та здивувати друзів, а недругів щє більше. Рекомендую.',
        800);

insert into items_imgs(item_id, path_to_img)
values (3, 'https://content2.rozetka.com.ua/goods/images/big/291254043.jpg');
insert into items_imgs(item_id, path_to_img)
values (3, 'https://content2.rozetka.com.ua/goods/images/big/291254055.jpg');

insert into items_categories (item_id, category_id)values (3, 7);
insert into items_categories (item_id, category_id)values (3, 2);
insert into items_categories (item_id, category_id)values (3, 1);

insert into items(person_id, name, description, price) --4
values (3, 'Затискач тримач для грошей карток чорний Classic Button Black',
        'Тримач для грошей зі 100% натуральної шкіри з фіксацією на кнопці

        Модель: Classic Button Black

        ⠀

        -Матеріал: натуральна шкіра Crazy Horse

        -Колір: чорний

        -Розмір: 11 см х 8 см х 1 см

        -2 відділення для карт, міститься до 3 карт в одну

        -Товщина шкіри: 1.5 мм

        -Все дуже акуратно зроблено

        -Підходить під усі купюри

        Стильний, якісний та зручний

        Виробництво: Україна

        .',
        645);

insert into items_imgs(item_id, path_to_img)
values (4, 'https://content.rozetka.com.ua/goods/images/big/289544689.jpg');
insert into items_imgs(item_id, path_to_img)
values (4, 'https://content.rozetka.com.ua/goods/images/big/289544720.jpg');
insert into items_imgs(item_id, path_to_img)
values (4, 'https://content.rozetka.com.ua/goods/images/big/289544735.jpg');

insert into items_categories (item_id, category_id)values (4, 5);
insert into items_categories (item_id, category_id)values (4, 9);